version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: directus_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    directus:
        image: directus/directus:latest
        container_name: directus_app
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8055:8055'
        environment:
            KEY: ${KEY}
            SECRET: ${SECRET}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            PUBLIC_URL: ${PUBLIC_URL}
            DB_CLIENT: postgres
            DB_HOST: postgres
            DB_PORT: 5432
            DB_DATABASE: ${POSTGRES_DB}
            DB_USER: ${POSTGRES_USER}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
            STORAGE_LOCAL_DRIVER: ${STORAGE_LOCAL_DRIVER}
            STORAGE_LOCAL_ROOT: ${STORAGE_LOCAL_ROOT}
            CORS_ENABLED: true
            CORS_ORIGIN: http://localhost:5173
        volumes:
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
            - ./backups:/directus/backups
        depends_on:
            - postgres

volumes:
    postgres_data:
